#!/usr/bin/env python3
"""Pin cross-game release-target lineage for shared TH02/TH04/TH05 ZUNINIT helpers."""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import tomllib

ROOT = Path(__file__).resolve().parents[2]
TARGETS = ROOT / "config/targets.toml"
V489 = ROOT / ".analysis/gpt-web/v489-bgimage-hybrid-replay-003/a/op/source"
TH04_PAYLOAD = ROOT / ".analysis/reconstruction/v218-th04-zun-diet/payload.bin"
TH04_PAYLOAD_SHA = "baf5a58b333af1135d67c7dd7a4f86e2c828ae149c8219d5d1f589073b0bde9e"

COMPONENTS = {
    "th02": {
        "artifact": "th02-zun-smoke",
        "linked": V489 / "bin/th02/zuninit.com",
        "size": 0x56E,
        "sha256": "27fe52738878c1fa267c5dc82b0d70957d72dca5a6da375620a74d163b61e2d8",
        "target_offset": 1476,
    },
    "th04": {
        "artifact": "th04-zun",
        "size": 0x475,
        "sha256": "692b1e056d907a9649bd1effa6e83239f71039d17de3569464067d0b42b7aa5e",
        "payload_offset": 0x6F3,
    },
    "th05": {
        "artifact": "th05-zun-smoke",
        "linked": V489 / "bin/th05/zuninit.com",
        "size": 0x3F1,
        "sha256": "6091d53910b5a4bbcd132d663dc9531d8ea65cff95baf4307a3cd5e768e1e8b1",
        "target_offset": 1779,
    },
}

# Runtime COM offsets inside each ZUNINIT component.
CONVERTERS = {
    "th02": (0x1F0, 0x12),
    "th04": (0x1BD, 0x12),
    "th05": (0x19C, 0x12),
}
RENDERERS = {
    "th02": (0x202, 0x3B),
    "th04": (0x1CF, 0x3B),
    "th05": (0x1AE, 0x3C),
}
CONVERTER_SHA = "044ce9480a0506ffac42aeaf78844e0266262c10ffd075d2c861a7a78689adf8"
RENDERER_TH02_TH04_SHA = "0c5a90f8b85153d3c668f033651cddedbe2a635e2cfdcf8345e4ec5f8f8c6fb6"

IDA_MARKER = b"This file has been generated by The Interactive Disassembler (IDA)"


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def manifest() -> dict[str, dict[str, object]]:
    parsed = tomllib.loads(TARGETS.read_text(encoding="utf-8"))
    return {row["id"]: row for row in parsed["artifacts"]}


def locate_all(haystack: bytes, needle: bytes) -> list[int]:
    out: list[int] = []
    pos = haystack.find(needle)
    while pos >= 0:
        out.append(pos)
        pos = haystack.find(needle, pos + 1)
    return out


def slice_runtime(component: bytes, runtime: int, size: int) -> bytes:
    local = runtime - 0x100
    if local < 0 or local + size > len(component):
        raise RuntimeError("cross-game ZUNINIT function extent escaped component")
    return component[local:local + size]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--output-dir", type=Path, required=True)
    args = ap.parse_args()
    output = args.output_dir.resolve()
    private = (ROOT / ".analysis/reconstruction/probes").resolve()
    if output.exists() or output.parent != private:
        ap.error("output must be a new direct child of .analysis/reconstruction/probes")

    targets = manifest()
    payload = TH04_PAYLOAD.read_bytes()
    if sha(payload) != TH04_PAYLOAD_SHA:
        raise RuntimeError("TH04 decoded ZUN payload identity drift")

    components: dict[str, bytes] = {}
    target_receipts: dict[str, object] = {}

    for game, spec in COMPONENTS.items():
        info = targets[str(spec["artifact"])]
        target_path = ROOT / str(info["private_path"])
        target = target_path.read_bytes()
        if len(target) != int(info["size"]) or sha(target) != str(info["sha256"]):
            raise RuntimeError(f"{game}: private release target identity drift")

        if game == "th04":
            start = int(spec["payload_offset"])
            comp = payload[start:start + int(spec["size"])]
            matches = [start]
            target_coordinate = "decoded ZUN payload"
        else:
            linked = Path(spec["linked"]).read_bytes()
            if len(linked) != int(spec["size"]) or sha(linked) != str(spec["sha256"]):
                raise RuntimeError(f"{game}: retained ZUNINIT locator component drift")
            matches = locate_all(target, linked)
            if matches != [int(spec["target_offset"])]:
                raise RuntimeError(f"{game}: ZUNINIT component is not uniquely located: {matches}")
            comp = target[matches[0]:matches[0] + int(spec["size"])]
            target_coordinate = "release ZUN.COM file"

        if len(comp) != int(spec["size"]) or sha(comp) != str(spec["sha256"]):
            raise RuntimeError(f"{game}: release-target ZUNINIT component identity drift")
        components[game] = comp

        asm = V489 / f"{game}_zuninit.asm"
        asm_bytes = asm.read_bytes()
        if IDA_MARKER not in asm_bytes:
            raise RuntimeError(f"{game}: retained candidate no longer carries IDA-generated header")

        target_receipts[game] = {
            "artifact": spec["artifact"],
            "target_sha256": info["sha256"],
            "component_coordinate": target_coordinate,
            "component_matches": matches,
            "component_size": len(comp),
            "component_sha256": sha(comp),
            "candidate_asm_ida_generated_header": True,
            "candidate_asm_sha256": sha(asm_bytes),
        }

    converters = {}
    converter_bytes = []
    for game, (runtime, size) in CONVERTERS.items():
        body = slice_runtime(components[game], runtime, size)
        converters[game] = {
            "runtime_com_offset": hex(runtime),
            "size": size,
            "sha256": sha(body),
            "bytes_hex": body.hex(),
        }
        converter_bytes.append(body)
    if any(body != converter_bytes[0] for body in converter_bytes[1:]):
        raise RuntimeError("TH02/TH04/TH05 ZUNINIT SJIS converter bytes are no longer identical")
    if sha(converter_bytes[0]) != CONVERTER_SHA:
        raise RuntimeError("shared ZUNINIT SJIS converter identity drift")

    renderers = {}
    renderer_bytes = {}
    for game, (runtime, size) in RENDERERS.items():
        body = slice_runtime(components[game], runtime, size)
        renderer_bytes[game] = body
        renderers[game] = {
            "runtime_com_offset": hex(runtime),
            "size": size,
            "sha256": sha(body),
            "bytes_hex": body.hex(),
        }
    if renderer_bytes["th02"] != renderer_bytes["th04"]:
        raise RuntimeError("TH02/TH04 ZUNINIT VRAM renderer bytes are no longer identical")
    if sha(renderer_bytes["th04"]) != RENDERER_TH02_TH04_SHA:
        raise RuntimeError("shared TH02/TH04 ZUNINIT renderer identity drift")
    if renderer_bytes["th05"] == renderer_bytes["th04"]:
        raise RuntimeError("TH05 renderer unexpectedly stopped being the evolved implementation")

    receipt = {
        "schema_version": 1,
        "observed_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "claim_scope": "cross-game release-target lineage for ZUNINIT shared support functions",
        "targets": target_receipts,
        "sjis_converter": {
            "games": converters,
            "all_three_release_targets_byte_identical": True,
            "shared_sha256": CONVERTER_SHA,
            "th04_payload_extent": "0x7B0..0x7C1",
        },
        "vram_text_renderer": {
            "games": renderers,
            "th02_th04_release_targets_byte_identical": True,
            "shared_th02_th04_sha256": RENDERER_TH02_TH04_SHA,
            "th05_is_evolved_nonidentical_implementation": True,
            "th04_payload_extent": "0x7C2..0x7FC",
        },
        "source_provenance": {
            "all_retained_th02_th04_th05_candidate_asm_files_are_ida_generated": True,
            "exactness_credit": False,
            "conclusion": (
                "Release-target equality proves cross-version shared implementation lineage, "
                "but the retained ASM files remain reverse-engineered candidates and do not "
                "establish original source provenance."
            ),
        },
        "limit": (
            "This receipt is source-ownership/lineage evidence only. It does not promote either "
            "TH04 function to exact source acceptance."
        ),
    }
    output.mkdir()
    path = output / "receipt.json"
    path.write_text(json.dumps(receipt, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({
        "receipt": str(path),
        "converter_sha256": CONVERTER_SHA,
        "renderer_th02_th04_sha256": RENDERER_TH02_TH04_SHA,
    }, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
