#!/usr/bin/env python3
"""Audit pinned ReC98 history for the ZUN resident self-assignment barriers."""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[2]
REPO = ROOT / "_reference/ReC98"
PINNED_HEAD = "b6ba5b0a529edbb31efdf8c0e939263804f8ee47"
INTRO = "b8ca607c385d0ddc2a776cfca910b263ebb069cb"
SPLIT = "9ae9754fb35459e74ed220a4a33ee919d86c4805"
CPP_MIGRATION = "7a44adf8d03abf002bf7944fb112fae6e1d3d564"
CONSOLIDATE = "0c682b5bc00584973ffdf56764262f58761e6ab3"


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def git(*args: str) -> bytes:
    return subprocess.run(
        ["git", "-C", str(REPO), *args],
        check=True, capture_output=True,
    ).stdout


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()
    output = args.output_dir.resolve()
    private = (ROOT / ".analysis/reconstruction/probes").resolve()
    if output.exists() or output.parent != private:
        parser.error("output directory must be new directly below .analysis/reconstruction/probes")
    if git("rev-parse", "HEAD").decode().strip() != PINNED_HEAD:
        raise RuntimeError("pinned ReC98 HEAD drift")
    subprocess.run(
        ["git", "-C", str(REPO), "merge-base", "--is-ancestor", INTRO, PINNED_HEAD],
        check=True,
    )

    intro_message = git("show", "-s", "--format=%B", INTRO).decode("utf-8")
    intro_diff = git("show", "--format=", "--no-ext-diff", INTRO, "--", "th02/zun_res1.c")
    required_message_fragments = (
        "correct decompilation",
        "no-ops generated by assigning variables",
        "optimization barrier",
        "ZUN could have actually written this",
    )
    if not all(fragment in intro_message for fragment in required_message_fragments):
        raise RuntimeError("barrier introduction commit message drift")
    for fragment in (
        b"sgm = sgm; /* optimization barrier #1 */",
        b"argv = argv; /* optimization barrier #2 */",
    ):
        if fragment not in intro_diff:
            raise RuntimeError("barrier introduction diff drift")

    split_diff = git("show", "--format=", "--no-ext-diff", SPLIT, "--", "th02/zun_res1.c", "th02/res_init.c")
    split_file = git("show", f"{SPLIT}:th02/res_init.c")
    if b"optimization barrier #1" not in split_file or b"optimization barrier #2" not in split_file:
        raise RuntimeError("resident split no longer preserves barriers")

    cpp_diff = git("show", "--format=", "--no-ext-diff", CPP_MIGRATION, "--", "th02/res_init.c", "th02/res_init.cpp")
    cpp_file = git("show", f"{CPP_MIGRATION}:th02/res_init.cpp")
    if b"optimization barrier #1" not in cpp_file or b"optimization barrier #2" not in cpp_file:
        raise RuntimeError("C++ migration no longer preserves barriers")

    consolidate_message = git("show", "-s", "--format=%B", CONSOLIDATE)
    if b"optimization_barrier()" not in consolidate_message:
        raise RuntimeError("barrier consolidation history drift")

    output.mkdir()
    receipt = {
        "schema_version": 1,
        "observed_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "claim_scope": "Pinned ReC98 provenance of TH02/TH04 resident optimization barriers; upstream-only negative source authority",
        "reference_head": PINNED_HEAD,
        "introduction_commit": INTRO,
        "introduction_subject": git("show", "-s", "--format=%s", INTRO).decode().strip(),
        "introduction_message_sha256": sha(intro_message.encode()),
        "introduction_diff_sha256": sha(intro_diff),
        "split_commit": SPLIT,
        "split_diff_sha256": sha(split_diff),
        "split_file_sha256": sha(split_file),
        "cpp_migration_commit": CPP_MIGRATION,
        "cpp_migration_diff_sha256": sha(cpp_diff),
        "cpp_migration_file_sha256": sha(cpp_file),
        "consolidation_commit": CONSOLIDATE,
        "consolidation_message_sha256": sha(consolidate_message),
        "observations": {
            "introduced_as_decompilation_work": True,
            "self_assignment_barriers_introduced_in_diff": True,
            "commit_message_calls_them_no_ops": True,
            "commit_message_explains_tail_fold_barrier_effect": True,
            "commit_message_only_speculates_that_zun_could_have_written_them": True,
            "barriers_preserved_by_later_maintenance": True,
        },
        "conclusion": (
            "Pinned ReC98 history identifies the self-assignment statements as a "
            "decompilation/codegen workaround and offers only speculation that ZUN "
            "might have written them. It supplies no independent original-source "
            "provenance for importing those inert statements into maintained TH04 source."
        ),
        "limit": (
            "This is upstream provenance only. It does not prove what the original "
            "TH04 source contained and grants zero exactness credit."
        ),
    }
    path = output / "receipt.json"
    path.write_text(json.dumps(receipt, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(receipt["observations"], sort_keys=True))
    print(f"receipt: {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
