#!/usr/bin/env python3
"""Pin negative source provenance for TH04 ZUNINIT/MEMCHK candidate assembly."""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[2]
REF = ROOT / "_reference/ReC98"
PINNED = "b6ba5b0a529edbb31efdf8c0e939263804f8ee47"
IDA_MARKER = b"This file has been generated by The Interactive Disassembler (IDA)"

FILES = {
    "zuninit": {
        "path": "th04_zuninit.asm",
        "history": ["f54cd0fe95d393b793d521b0df08f16dd725b1d5"],
        "intro": "f54cd0fe95d393b793d521b0df08f16dd725b1d5",
        "current_sha256": "bbc719c05ec8cb945e13f4dfbbc1a161f172a1bfca2e34ca1afbc92d645578d3",
        "intro_sha256": "bbc719c05ec8cb945e13f4dfbbc1a161f172a1bfca2e34ca1afbc92d645578d3",
    },
    "memchk": {
        "path": "th04_memchk.asm",
        "history": [
            "6212a4c21ba7c0acb8652f676ca2c31ac565a916",
            "90b7ace180c23bfb9b5b23e61ef8a1cb431a18da",
        ],
        "intro": "90b7ace180c23bfb9b5b23e61ef8a1cb431a18da",
        "current_sha256": "1fdc9a959a6bb03b8df9dff4471d2342ef1aabe76cccddbdaba7dd69c67bdc20",
        "intro_sha256": "6fdc37440ea5ed69ab85ffa2e56c061b3f9c17842a2797d87ae8789af6634789",
    },
}


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def git(*args: str) -> bytes:
    completed = subprocess.run(
        ["git", *args], cwd=REF, capture_output=True, check=True
    )
    return completed.stdout


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()
    output = args.output_dir.resolve()
    private = (ROOT / ".analysis/reconstruction/probes").resolve()
    if output.exists() or output.parent != private:
        parser.error("output directory must be new directly below .analysis/reconstruction/probes")

    if git("rev-parse", PINNED).decode().strip() != PINNED:
        raise RuntimeError("pinned ReC98 revision unavailable")
    output.mkdir(parents=True)

    results = {}
    for label, info in FILES.items():
        path = str(info["path"])
        history = git("log", "--format=%H", PINNED, "--", path).decode().splitlines()
        if history != info["history"]:
            raise RuntimeError(f"{label}: pinned path history drift: {history!r}")

        current = git("show", f"{PINNED}:{path}")
        intro = git("show", f"{info['intro']}:{path}")
        if sha(current) != info["current_sha256"] or sha(intro) != info["intro_sha256"]:
            raise RuntimeError(f"{label}: source identity drift")
        if IDA_MARKER not in current or IDA_MARKER not in intro:
            raise RuntimeError(f"{label}: IDA provenance header missing")

        intro_message = git(
            "show", "-s", "--format=%H%n%aI%n%s%n%b", str(info["intro"])
        ).decode("utf-8")
        if "Initial state" not in intro_message:
            raise RuntimeError(f"{label}: introduction commit no longer initial-state import")

        result = {
            "path": path,
            "history": history,
            "intro_commit": info["intro"],
            "intro_sha256": sha(intro),
            "current_sha256": sha(current),
            "ida_generated_header": True,
            "intro_message": intro_message,
        }
        if label == "zuninit":
            if "need some RE attention" not in intro_message:
                raise RuntimeError("ZUNINIT intro no longer documents unresolved RE status")
        else:
            later = git(
                "show", "-s", "--format=%H%n%aI%n%s%n%b",
                "6212a4c21ba7c0acb8652f676ca2c31ac565a916",
            ).decode("utf-8")
            if "False positives: 0xFF / 255 / -1" not in later:
                raise RuntimeError("MEMCHK follow-up PI-false-positive provenance drift")
            diff = git(
                "diff", "90b7ace180c23bfb9b5b23e61ef8a1cb431a18da",
                "6212a4c21ba7c0acb8652f676ca2c31ac565a916", "--", path,
            ).decode("cp932", errors="replace")
            if "-		mov	ax, 0FFh" not in diff or "+		mov	ax, 255" not in diff:
                raise RuntimeError("MEMCHK only follow-up no longer matches literal spelling change")
            result["followup_commit"] = "6212a4c21ba7c0acb8652f676ca2c31ac565a916"
            result["followup_scope"] = "0FFh literal spelling changed to 255 for PI false-positive handling"

        results[label] = result

    receipt = {
        "schema_version": 1,
        "observed_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "claim_scope": "negative original-source provenance for TH04 ZUNINIT/MEMCHK candidate assembly",
        "pinned_rec98_revision": PINNED,
        "files": results,
        "conclusion": (
            "Both candidate assembly files enter the pinned ReC98 ancestry as IDA-generated "
            "initial-state reconstructions, not independently sourced original assembly. "
            "MEMCHK's only later path change is a literal-spelling PI false-positive fix. "
            "These files remain target-derived hypotheses even when their linked components raw-match."
        ),
        "limit": (
            "This is upstream-history provenance only. It does not prove what source form ZUN "
            "originally authored and grants no target/source/exactness credit."
        ),
    }
    path = output / "receipt.json"
    path.write_text(json.dumps(receipt, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"receipt": str(path), "files": list(results)}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
