#include "configuration.hpp"
#include <algorithm>
#include <fstream>
#include <iostream>
#include <sstream>
#include <stdexcept>
using namespace th04::portable;
namespace {
configuration::Bytes bytes(std::string text) {
    if(text=="-")return {};
    if(text.size()%2)throw std::runtime_error("invalid hex");configuration::Bytes out;
    for(std::size_t i=0;i<text.size();i+=2)out.push_back(std::uint8_t(std::stoul(text.substr(i,2),nullptr,16)));
    return out;
}
std::string hex(const configuration::Bytes& b) {
    if(b.empty())return "-";std::string s;const char* h="0123456789abcdef";
    for(auto v:b){s+=h[v>>4];s+=h[v&15];}return s;
}
void print(const configuration::Result& r) {
    std::cout<<"STATE "<<hex({r.options.begin(),r.options.end()})<<' '<<hex(r.file)<<'\n';
    for(const auto& o:r.operations)std::cout<<unsigned(o.kind)<<' '<<o.a<<' '<<o.b<<' '<<hex(o.data)<<'\n';
}
}
int main(int argc,char** argv) {
    try {
        if(argc==3 && std::string(argv[1])=="--replay") {
            std::ifstream f(argv[2]);unsigned operation;std::string raw,options;
            while(f>>operation>>raw>>options) {
                auto file=bytes(raw);auto b=bytes(options);if(b.size()!=6)throw std::runtime_error("options need6bytes");
                configuration::Options o{};std::copy(b.begin(),b.end(),o.begin());
                print(operation==0 ? configuration::load(file) : configuration::save(file,o,operation==2));
            }
            return 0;
        }
        if(argc==4 && std::string(argv[1])=="--host") {
            // Physical controls are generated by the independent Python driver.
            const auto o=bytes(argv[3]);if(o.size()!=6)throw std::runtime_error("options need6bytes");
            configuration::Options raw{};std::copy(o.begin(),o.end(),raw.begin());
            configuration::HostStore store(argv[2]);
            const auto loaded=configuration::encode(store.options());
            std::cout<<"LOAD "<<hex({loaded.begin(),loaded.end()})<<'\n';
            if(store.setup_required())store.complete_setup(2,1);
            store.save(configuration::decode(raw),false);
            configuration::HostStore reopen(argv[2]);print(configuration::load(reopen.bytes()));
            reopen.save(configuration::decode(raw),true);
            configuration::HostStore exit_reopen(argv[2]);print(configuration::load(exit_reopen.bytes()));return 0;
        }
        if(argc!=1)throw std::runtime_error("configuration contracts CLI");
        const configuration::Options raw{255,0,3,3,3,255};
        const configuration::Bytes initial{1,3,2,2,1,1,0xa5,0x12,0x7e,10};
        const auto live=configuration::save(initial,raw,false);
        if(live.file[6]!=0xa5 || live.file[7]!=0x12 || live.file[8]!=0x7e || live.file[9]!=7 ||
            live.operations.size()!=6 || live.operations[3].kind!=configuration::IO::seek || live.operations[3].a!=9)
            throw std::runtime_error("configuration live-save metadata/checksum boundary");
        const configuration::Options corrected{255,3,2,0,0,255};
        if(configuration::load(live.file).options!=corrected)throw std::runtime_error("configuration raw-byte/range contract");
        const auto exiting=configuration::save(initial,raw,true);
        if(exiting.file[6] || exiting.file[7] || exiting.file[8] || exiting.file[9]!=7 || exiting.operations.size()!=4)
            throw std::runtime_error("configuration exit clears complete metadata");
        std::cout<<"configuration contracts PASS\n";return 0;
    } catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}
}
