#include "application_state.hpp"
#include "bullet_geometry.hpp"
#include "item_system.hpp"
#include "menu_state.hpp"
#include "random_lcg.hpp"
#include "random_ring.hpp"
#include "selection_state.hpp"

#include <array>
#include <cstdint>
#include <iostream>
#include <stdexcept>

namespace bullet = th04::portable::bullet;
namespace menu = th04::portable::menu;
namespace application = th04::portable::application;
namespace item = th04::portable::item;
namespace rng = th04::portable::rng;
namespace randring = th04::portable::randring;
namespace selection = th04::portable::selection;

namespace {

void require(bool condition, const char* message) {
    if (!condition) {
        throw std::runtime_error(message);
    }
}

template <size_t Size>
void require_spread(
    std::uint8_t count, bullet::Angle step,
    const std::array<unsigned, Size>& expected
) {
    require(count == Size, "spread fixture count mismatch");
    for (std::uint16_t member = 0; member < count; ++member) {
        require(
            bullet::spread_member_angle(member, count, step) == expected[member],
            "spread angle mismatch"
        );
    }
}

} // namespace

int main() {
    static_assert(sizeof(void*) == 8, "portable build must be 64-bit");
    static_assert(sizeof(bullet::Angle) == 1, "bullet angle storage must be one byte");
    static_assert(sizeof(bullet::GroupCode) == 1, "spawn group storage must be one byte");
    static_assert(BG_RING == 0x26 && BG_RING_AIMED == 0x2c);
    static_assert(BG_SPREAD == 0x2d && BG_SPREAD_AIMED == 0x2e);

    require_spread<5>(5, 0x10, {0x00, 0xf0, 0x10, 0xe0, 0x20});
    require_spread<4>(4, 0x10, {0x08, 0xf8, 0x18, 0xe8});
    require_spread<5>(5, 0x90, {0x00, 0x70, 0x90, 0xe0, 0x20});

    const std::array<unsigned, 8> ring{
        0x00, 0x20, 0x40, 0x60, 0x80, 0xa0, 0xc0, 0xe0
    };
    for (std::uint16_t member = 0; member < ring.size(); ++member) {
        require(
            bullet::ring_member_angle(member, std::uint8_t(ring.size())) ==
                ring[member],
            "ring angle mismatch"
        );
    }
    require(
        bullet::apply_aim_and_rotation(0xf0, true, 0x20, 0x08) == 0x18,
        "aim/template rotation wrap mismatch"
    );
    require(
        bullet::apply_aim_and_rotation(0xf0, false, 0x20, 0x08) == 0xf8,
        "un-aimed template rotation mismatch"
    );

    require(bullet::directional_sprite_cel(0x00) == 0, "right-facing cel mismatch");
    require(bullet::directional_sprite_cel(0x04) == 0, "rounded cel mismatch");
    require(bullet::directional_sprite_cel(0x05) == 1, "next cel mismatch");
    require(bullet::directional_sprite_cel(0x7c) == 15, "last cel mismatch");
    require(bullet::directional_sprite_cel(0x80) == 0, "half-turn reuse mismatch");

    bool rejected = false;
    try {
        (void)bullet::ring_member_angle(0, 0);
    } catch (const std::out_of_range&) {
        rejected = true;
    }
    require(rejected, "portable ring must reject count zero");

    static_assert(sizeof(std::uint32_t) == 4, "LCG state must be 32-bit");
    rng::Lcg32 default_lcg;
    struct LcgVector {
        std::uint32_t state;
        std::uint16_t result;
    };
    const std::array<LcgVector, 3> default_vectors{{
        {0x015a4e36u, 346},
        {0x8082a52fu, 130},
        {0xaae684bcu, 10982},
    }};
    for (const auto& vector : default_vectors) {
        require(default_lcg.next15() == vector.result, "default LCG result mismatch");
        require(default_lcg.state() == vector.state, "default LCG state mismatch");
    }

    rng::Lcg32 demo_lcg(rng::Lcg32::demo_seed);
    require(demo_lcg.next15() == 11821, "demo LCG first result mismatch");
    require(demo_lcg.state() == 0xae2d25d7u, "demo LCG first state mismatch");
    require(demo_lcg.next15() == 30070, "demo LCG second result mismatch");
    require(demo_lcg.state() == 0xf5765784u, "demo LCG second state mismatch");

    rng::Lcg32 wrapping_lcg(UINT32_MAX);
    require(wrapping_lcg.next15() == 32421, "LCG wrap result mismatch");
    require(wrapping_lcg.state() == 0xfea5b1ccu, "LCG wrap state mismatch");

    randring::SharedRandomRing shared_random_ring;
    std::uint16_t generated_byte = 0;
    const auto fill_shared_random_ring = [&]() {
        generated_byte = 0;
        shared_random_ring.fill([&]() {
            return static_cast<std::uint8_t>(generated_byte++);
        });
        require(generated_byte == 256, "random-ring fill count mismatch");
        require(
            shared_random_ring.cursor() == 0,
            "random-ring fill cursor mismatch"
        );
    };
    fill_shared_random_ring();

    // Generated bytes 00..FF are stored at ring indexes 255..0. Alternating
    // plain, AND and MOD calls proves that every operation advances one state.
    require(
        shared_random_ring.next16() == 0xfeff,
        "random-ring first word mismatch"
    );
    require(shared_random_ring.next16_and(0x000f) == 0x000e,
            "random-ring AND reduction mismatch");
    require(shared_random_ring.next16_mod(100) == 65,
            "random-ring MOD reduction mismatch");
    require(
        shared_random_ring.cursor() == 3,
        "random-ring shared cursor mismatch"
    );

    fill_shared_random_ring();
    std::uint16_t last_ordinary_sample = 0;
    for (std::size_t i = 0; i < 255; ++i) {
        last_ordinary_sample = shared_random_ring.next16();
    }
    require(last_ordinary_sample == 0x0001,
            "random-ring last in-array sample mismatch");
    require(shared_random_ring.cursor() == 255,
            "random-ring pre-wrap cursor mismatch");
    require(shared_random_ring.next16() == 0xff00,
            "random-ring cursor-adjacent wrap sample mismatch");
    require(shared_random_ring.cursor() == 0,
            "random-ring low-byte wrap mismatch");
    require(shared_random_ring.next16() == 0xfeff,
            "random-ring post-wrap sequence mismatch");

    fill_shared_random_ring();
    bool zero_divisor_rejected = false;
    try {
        (void)shared_random_ring.next16_mod(0);
    } catch (const std::domain_error&) {
        zero_divisor_rejected = true;
    }
    require(zero_divisor_rejected, "random-ring zero divisor must fail");
    require(shared_random_ring.cursor() == 1,
            "random-ring zero divisor must consume its sample first");

    rng::Lcg32 ring_lcg;
    randring::SharedRandomRing generated_random_ring;
    generated_random_ring.fill(ring_lcg);
    require(ring_lcg.state() == 0x97493301u,
            "random-ring fill must consume 256 LCG states");
    require(generated_random_ring.next16() == 0x4649,
            "LCG-backed descending random-ring fill mismatch");

    static_assert(sizeof(item::Subpixel) == 2, "item subpixels must be 16-bit");
    static_assert(sizeof(item::Type) == 1, "item type must be byte-sized");

    item::EnemyDropSequence enemy_drop_sequence;
    enemy_drop_sequence.initialize(ring_lcg);
    require(enemy_drop_sequence.cycle() == 11,
            "item drop seed must follow the 256-byte LCG ring fill");
    const auto first_enemy_drop = enemy_drop_sequence.next();
    require(first_enemy_drop && *first_enemy_drop == item::Type::power,
            "first seeded automatic enemy drop mismatch");
    require(!enemy_drop_sequence.next(),
            "automatic enemy drop must skip every odd counter value");
    item::EnemyDropSequence final_drop_entry(125);
    require(final_drop_entry.next() == item::Type::big_power,
            "automatic enemy drop table final entry mismatch");
    require(!final_drop_entry.next(),
            "automatic enemy drop table must retain half-rate cadence");

    randring::SharedRandomRing item_random_ring;
    const auto fill_item_random_ring = [&]() {
        std::uint16_t generated = 0;
        item_random_ring.fill([&]() {
            return static_cast<std::uint8_t>(generated++);
        });
        require(generated == 256, "item random-ring fill count mismatch");
    };
    std::bitset<item::pool_size> all_item_slots_free;
    all_item_slots_free.set();
    fill_item_random_ring();
    const auto miss_drop = item::spawn_miss_items(
        item_random_ring, item::to_subpixel(192), 3, all_item_slots_free
    );
    require(miss_drop.count == 5 && miss_drop.big_power_slot == 4 &&
                miss_drop.discarded_distinct_slot == 2 &&
                miss_drop.ring_samples_consumed == 6 &&
                item_random_ring.cursor() == 6,
            "miss-drop selection and random consumption mismatch");
    const std::array<item::Type, 5> miss_types{{
        item::Type::point,
        item::Type::power,
        item::Type::point,
        item::Type::power,
        item::Type::big_power,
    }};
    const std::array<item::Velocity, 5> center_velocities{{
        {-24, -48}, {-12, -56}, {0, -64}, {12, -56}, {24, -48},
    }};
    for (std::size_t i = 0; i < miss_types.size(); ++i) {
        require(miss_drop.spawns[i].pool_index == i &&
                    miss_drop.spawns[i].drop_slot == i &&
                    miss_drop.spawns[i].type == miss_types[i] &&
                    miss_drop.spawns[i].velocity.x == center_velocities[i].x &&
                    miss_drop.spawns[i].velocity.y == center_velocities[i].y,
                "miss-drop slot/type/velocity mismatch");
    }

    fill_item_random_ring();
    const auto last_life_drop = item::spawn_miss_items(
        item_random_ring, item::to_subpixel(192), 1, all_item_slots_free
    );
    require(last_life_drop.ring_samples_consumed == 6,
            "last-life override must preserve random consumption");
    for (std::size_t i = 0; i < last_life_drop.count; ++i) {
        require(last_life_drop.spawns[i].type == item::Type::full_power,
                "last-life miss drop must become full power");
    }

    std::bitset<item::pool_size> sparse_item_slots;
    sparse_item_slots.set(3);
    sparse_item_slots.set(31);
    fill_item_random_ring();
    const auto truncated_drop = item::spawn_miss_items(
        item_random_ring, item::to_subpixel(192), 3, sparse_item_slots
    );
    require(truncated_drop.count == 2 &&
                truncated_drop.spawns[0].pool_index == 3 &&
                truncated_drop.spawns[1].pool_index == 31 &&
                truncated_drop.ring_samples_consumed == 4 &&
                item_random_ring.cursor() == 4,
            "full item pool must truncate without displacing live entries");

    item::ScoreState ordinary_overflow;
    ordinary_overflow.power = item::power_max;
    ordinary_overflow.power_overflow = 41;
    const auto ordinary_overflow_effect = item::collect(
        ordinary_overflow, item::Type::power, item::to_subpixel(100), false
    );
    require(ordinary_overflow.power_overflow == 42 &&
                ordinary_overflow_effect.base_points == 1280 &&
                ordinary_overflow_effect.yellow_point_number,
            "ordinary power overflow cap mismatch");

    item::ScoreState big_overflow;
    big_overflow.power = item::power_max;
    big_overflow.power_overflow = 41;
    const auto big_overflow_effect = item::collect(
        big_overflow, item::Type::big_power, item::to_subpixel(100), false
    );
    require(big_overflow.power_overflow == 42 &&
                big_overflow_effect.base_points == 2560 &&
                big_overflow_effect.awarded_points == 2560 &&
                big_overflow_effect.yellow_point_number,
            "safe above-cap big-power reward mismatch");

    bool invalid_item_state_rejected = false;
    try {
        item::ScoreState invalid_item_state;
        invalid_item_state.power_overflow = 43;
        (void)item::collect(
            invalid_item_state, item::Type::big_power,
            item::to_subpixel(100), false
        );
    } catch (const std::logic_error&) {
        invalid_item_state_rejected = true;
    }
    require(invalid_item_state_rejected,
            "portable item scorer must reject an invalid table index");

    item::ScoreState point_score;
    point_score.dream_score = 1280;
    point_score.item_playperf_raise = 24;
    const auto point_effect = item::collect(
        point_score, item::Type::point, item::to_subpixel(52), true
    );
    require(point_effect.base_points == 6400 &&
                point_effect.awarded_points == 12800 &&
                point_effect.yellow_point_number &&
                point_effect.playperf_raised == 1 &&
                point_score.item_playperf_raise == 0 &&
                point_score.score_delta == 12800 &&
                point_score.max_valued_point_items == 1 &&
                point_score.total_point_items_collected == 1 &&
                point_score.stage_point_items_collected == 1,
            "maximum point item/dream/Bomb multiplier mismatch");

    item::ScoreState dream_score;
    dream_score.dream_items_collected = 6;
    auto dream_effect = item::collect(
        dream_score, item::Type::dream, item::to_subpixel(100), false
    );
    require(dream_score.dream_items_collected == 7 &&
                dream_score.dream_score == 1280 &&
                dream_effect.base_points == 1280,
            "dream score final entry mismatch");
    dream_effect = item::collect(
        dream_score, item::Type::dream, item::to_subpixel(100), false
    );
    require(dream_score.dream_items_collected == 7 &&
                dream_effect.base_points == 1280,
            "dream score saturation mismatch");

    item::ScoreState missed_item;
    missed_item.item_playperf_lower = 63;
    const auto miss_effect = item::miss(missed_item, item::Type::power);
    require(miss_effect.playperf_lowered == 1 &&
                missed_item.item_playperf_lower == 16,
            "missed-item 64-minus-48 performance carry mismatch");

    constexpr auto player_x = item::to_subpixel(192);
    constexpr auto player_y = item::to_subpixel(320);
    require(item::overlaps_player_pickup_box(
                player_x, player_y,
                static_cast<item::Subpixel>(player_x + item::to_subpixel(24)),
                static_cast<item::Subpixel>(player_y - item::to_subpixel(14))),
            "pickup rectangle included corner mismatch");
    require(!item::overlaps_player_pickup_box(
                player_x, player_y,
                static_cast<item::Subpixel>(player_x + item::to_subpixel(25)),
                player_y),
            "pickup rectangle positive-X wrap rejection mismatch");
    require(!item::overlaps_player_pickup_box(
                player_x, player_y, player_x,
                static_cast<item::Subpixel>(player_y - item::to_subpixel(15))),
            "pickup rectangle asymmetric-Y rejection mismatch");

    menu::State locked_menu;
    locked_menu.handle(menu::Input::down);
    require(
        locked_menu.selection() == std::uint8_t(menu::MainChoice::scores),
        "locked Extra must be skipped moving down"
    );
    locked_menu.handle(menu::Input::up);
    require(
        locked_menu.selection() == std::uint8_t(menu::MainChoice::game),
        "locked Extra must be skipped moving up"
    );

    menu::State unlocked_menu(true);
    unlocked_menu.handle(menu::Input::down);
    require(
        unlocked_menu.selection() == std::uint8_t(menu::MainChoice::extra),
        "unlocked Extra must remain selectable"
    );

    menu::State option_menu;
    for (unsigned i = 0; i < 3; ++i) {
        option_menu.handle(menu::Input::down);
    }
    option_menu.handle(menu::Input::confirm);
    require(
        option_menu.screen() == menu::Screen::options &&
            option_menu.selection() == std::uint8_t(menu::OptionChoice::rank),
        "Option must enter at the Rank row"
    );
    option_menu.handle(menu::Input::left);
    require(option_menu.options().rank == 0, "rank left transition mismatch");
    option_menu.handle(menu::Input::left);
    require(option_menu.options().rank == 3, "rank wrap mismatch");
    option_menu.handle(menu::Input::down);
    option_menu.handle(menu::Input::left);
    option_menu.handle(menu::Input::left);
    option_menu.handle(menu::Input::left);
    require(option_menu.options().lives == 6, "lives wrap mismatch");
    option_menu.handle(menu::Input::down);
    option_menu.handle(menu::Input::right);
    require(option_menu.options().bombs == 0, "bombs wrap mismatch");
    option_menu.handle(menu::Input::down);
    option_menu.handle(menu::Input::right);
    require(option_menu.options().bgm_mode == 0, "BGM wrap mismatch");
    option_menu.handle(menu::Input::down);
    option_menu.handle(menu::Input::right);
    require(option_menu.options().se_mode == 0, "SE right order mismatch");
    option_menu.handle(menu::Input::right);
    require(option_menu.options().se_mode == 2, "SE right BEEP transition mismatch");
    option_menu.handle(menu::Input::left);
    require(option_menu.options().se_mode == 0, "SE left order mismatch");
    option_menu.handle(menu::Input::down);
    option_menu.handle(menu::Input::confirm);
    require(!option_menu.options().turbo, "confirm must toggle Turbo");
    option_menu.handle(menu::Input::down);
    option_menu.handle(menu::Input::confirm);
    require(option_menu.options() == menu::Options{}, "Reset defaults mismatch");
    option_menu.handle(menu::Input::down);
    option_menu.handle(menu::Input::confirm);
    require(
        option_menu.screen() == menu::Screen::main &&
            option_menu.selection() == std::uint8_t(menu::MainChoice::options),
        "Option Quit must return to the Option command"
    );
    const auto quit = option_menu.handle(menu::Input::cancel);
    require(quit.kind == menu::ResultKind::quit, "main Cancel must quit");

    selection::State normal_selection;
    normal_selection.handle(menu::Input::right);
    require(
        normal_selection.playchar() == application::Playchar::marisa,
        "character selection right transition mismatch"
    );
    normal_selection.handle(menu::Input::confirm);
    require(
        normal_selection.screen() == selection::Screen::shot_type &&
            normal_selection.shot_type() == application::ShotType::a,
        "shot selection entry mismatch"
    );
    normal_selection.handle(menu::Input::down);
    require(
        normal_selection.shot_type() == application::ShotType::b,
        "shot selection toggle mismatch"
    );
    const auto chosen_selection = normal_selection.handle(menu::Input::confirm);
    require(
        chosen_selection.kind == selection::ResultKind::chosen &&
            chosen_selection.playchar == application::Playchar::marisa &&
            chosen_selection.shot_type == application::ShotType::b,
        "character/shot result mismatch"
    );

    selection::Availability extra_availability{{
        {{false, true}},
        {{false, false}},
    }};
    selection::State extra_selection(extra_availability);
    extra_selection.handle(menu::Input::right);
    require(
        extra_selection.playchar() == application::Playchar::reimu,
        "locked Extra character must be skipped"
    );
    extra_selection.handle(menu::Input::confirm);
    require(
        extra_selection.shot_type() == application::ShotType::b,
        "Extra must enter on its first unlocked shot type"
    );
    extra_selection.handle(menu::Input::cancel);
    require(
        extra_selection.screen() == selection::Screen::playchar,
        "shot Cancel must return to character selection"
    );
    require(
        extra_selection.handle(menu::Input::cancel).kind ==
            selection::ResultKind::canceled,
        "character Cancel must return to title"
    );

    selection::State empty_selection({{{false, false}, {false, false}}});
    empty_selection.handle(menu::Input::confirm);
    const auto empty_chosen=empty_selection.handle(menu::Input::confirm);
    require(empty_chosen.kind==selection::ResultKind::chosen &&
            empty_chosen.playchar==application::Playchar::marisa &&
            empty_chosen.shot_type==application::ShotType::b,
            "original OP empty mask must retain Marisa/B fallback");

    application::State random_app;
    require(random_app.process_random_state() == rng::Lcg32::default_seed,
            "OP process LCG must begin at one");
    random_app.advance_op_menu_frame();
    random_app.advance_op_menu_frame();
    random_app.advance_op_menu_frame();
    require(random_app.resident().random_seed_source == 3,
            "OP menu frames must advance only the resident seed source");
    require(random_app.process_random_state() == rng::Lcg32::default_seed,
            "OP menu frames must not advance OP's process LCG");
    require(random_app.next_process_random() == 346,
            "OP process LCG must remain independent of the resident seed");
    require(random_app.resident().random_seed_source == 3,
            "OP process LCG must not publish into resident state");

    random_app.start_normal(
        application::Playchar::reimu, application::ShotType::a
    );
    require(random_app.process_random_state() == 3,
            "MAIN must copy the resident seed source once");
    require(random_app.next_process_random() == 1038,
            "MAIN resident-derived LCG sequence mismatch");
    random_app.finish_main({}, application::EndSequence::score);
    require(random_app.process_random_state() == rng::Lcg32::default_seed,
            "fresh MAINE must begin at one before verdict");
    random_app.seed_maine_verdict_random();
    require(random_app.process_random_state() == 3,
            "MAINE verdict must re-seed from resident state");
    random_app.finish_maine();
    require(random_app.process_random_state() == rng::Lcg32::default_seed,
            "fresh OP after MAINE must restore the process default");
    require(random_app.resident().random_seed_source == 3,
            "process transitions must retain the resident seed source");
    random_app.start_next_demo();
    require(random_app.process_random_state()==3,
            "demo high-score setup must use the resident-derived seed first");
    random_app.initialize_demo_stage();
    require(random_app.process_random_state() == rng::Lcg32::demo_seed,
            "recorded demo must override the resident-derived MAIN seed");
    random_app.return_from_main({});

    application::State app;
    require(
        app.program() == application::Program::op && app.generation() == 1,
        "portable application must begin in OP"
    );
    menu::Options custom_options;
    custom_options.lives = 5;
    custom_options.bombs = 1;
    custom_options.rank = 3;
    app.apply_options(custom_options);
    app.start_normal(
        application::Playchar::marisa, application::ShotType::b
    );
    require(
        app.program() == application::Program::main &&
            app.generation() == 2 && app.resident().stage == 0 &&
            app.resident().resource_stage == 0 &&
            app.resident().credit_lives == 5 &&
            app.resident().credit_bombs == 1 &&
            app.resident().playchar == application::Playchar::marisa &&
            app.resident().shot_type == application::ShotType::b &&
            app.resident().demo_number == 0 &&
            app.resident().end_sequence == application::EndSequence::in_game,
        "normal OP-to-MAIN resident contract mismatch"
    );

    bool invalid_transition_rejected = false;
    try {
        app.start_normal(
            application::Playchar::reimu, application::ShotType::a
        );
    } catch (const std::logic_error&) {
        invalid_transition_rejected = true;
    }
    require(
        invalid_transition_rejected,
        "MAIN must reject an OP-only launch transition"
    );

    application::RunStatistics statistics;
    statistics.score_digits = {1, 2, 3, 4, 5, 6, 7, 8};
    statistics.std_frames = 111;
    statistics.items_spawned = 222;
    statistics.items_collected = 123;
    statistics.point_items_collected = 77;
    statistics.max_valued_point_items_collected = 44;
    statistics.enemies_gone = 33;
    statistics.enemies_killed = 22;
    statistics.slow_frames = 0x12345678u;
    statistics.frames = 0x23456789u;
    app.finish_main(statistics, application::EndSequence::good);
    require(
        app.program() == application::Program::maine &&
            app.generation() == 3 &&
            app.maine_route() == application::MaineRoute::ending &&
            app.resident().end_type_ascii == '0' &&
            app.resident().score_digits == statistics.score_digits &&
            app.resident().statistics.frames == statistics.frames &&
            app.resident().statistics.slow_frames == statistics.slow_frames,
        "MAIN-to-MAINE publication contract mismatch"
    );
    app.finish_maine();
    require(
        app.program() == application::Program::op && app.generation() == 4 &&
            app.resident().score_digits == statistics.score_digits,
        "MAINE-to-OP resident retention mismatch"
    );

    app.start_normal(
        application::Playchar::marisa, application::ShotType::a
    );
    app.finish_main(statistics, application::EndSequence::bad);
    require(
        app.maine_route() == application::MaineRoute::ending &&
            app.resident().end_type_ascii == '1',
        "Bad Ending MAINE variant mismatch"
    );
    app.finish_maine();

    app.start_extra(
        application::Playchar::reimu, application::ShotType::a
    );
    require(
        app.resident().stage == 6 && app.resident().resource_stage == 6 &&
            app.resident().credit_lives == 3 &&
            app.resident().credit_bombs == 2,
        "Extra fixed-resource contract mismatch"
    );
    app.finish_main(statistics, application::EndSequence::extra);
    require(
        app.maine_route() == application::MaineRoute::extra,
        "Extra MAINE route mismatch"
    );
    app.finish_maine();

    app.start_normal(
        application::Playchar::reimu, application::ShotType::a
    );
    app.finish_main(statistics, application::EndSequence::score);
    require(
        app.maine_route() == application::MaineRoute::score_registration,
        "score-only MAINE route mismatch"
    );
    app.finish_maine();

    const std::array<std::uint8_t, 4> demo_stages{3, 0, 2, 1};
    const std::array<application::Playchar, 4> demo_characters{
        application::Playchar::reimu,
        application::Playchar::marisa,
        application::Playchar::reimu,
        application::Playchar::marisa,
    };
    const std::array<application::ShotType, 4> demo_shots{
        application::ShotType::a,
        application::ShotType::a,
        application::ShotType::b,
        application::ShotType::b,
    };
    for (std::size_t i = 0; i < demo_stages.size(); ++i) {
        app.start_next_demo();
        require(
            app.program() == application::Program::main &&
                app.resident().stage == 0 &&
                app.resident().resource_stage == demo_stages[i] &&
                app.resident().demo_stage == demo_stages[i] &&
                app.resident().demo_number == i + 1 &&
                app.resident().playchar == demo_characters[i] &&
                app.resident().shot_type == demo_shots[i] &&
                app.resident().credit_lives == 3 &&
                app.resident().credit_bombs == 3,
            "demo resident contract mismatch"
        );
        app.return_from_main(statistics);
        require(
            app.program() == application::Program::op,
            "demo completion must return directly to OP"
        );
    }
    app.start_next_demo();
    require(
        app.resident().demo_number == 1 &&
            app.resident().resource_stage == 3,
        "demo cycle must wrap from four to one"
    );
    app.return_from_main(statistics);
    app.exit_from_op();
    require(
        app.program() == application::Program::exited,
        "OP exit transition mismatch"
    );

    std::cout << "TH04 portable contracts: PASS pointer_bits="
              << sizeof(void*) * 8 << " angle_bits=" << sizeof(bullet::Angle) * 8
              << " menu_state=OP handoff_state=OP_MAIN_MAINE"
              << " selection=OP"
              << " randring=SHARED_OVERLAP lcg=PROCESS_LOCAL32"
              << " items=FIXED_WIDTH_SAFE" << std::endl;
    return 0;
}
