#include "application_state.hpp"
#include "bullet_geometry.hpp"
#include "menu_state.hpp"
#include "random_ring.hpp"

#include <array>
#include <cstdint>
#include <iostream>
#include <stdexcept>

namespace bullet = th04::portable::bullet;
namespace menu = th04::portable::menu;
namespace application = th04::portable::application;
namespace randring = th04::portable::randring;

namespace {

void require(bool condition, const char* message) {
    if (!condition) {
        throw std::runtime_error(message);
    }
}

template <size_t Size>
void require_spread(
    std::uint8_t count, bullet::Angle step,
    const std::array<unsigned, Size>& expected
) {
    require(count == Size, "spread fixture count mismatch");
    for (std::uint16_t member = 0; member < count; ++member) {
        require(
            bullet::spread_member_angle(member, count, step) == expected[member],
            "spread angle mismatch"
        );
    }
}

} // namespace

int main() {
    static_assert(sizeof(void*) == 8, "portable build must be 64-bit");
    static_assert(sizeof(bullet::Angle) == 1, "bullet angle storage must be one byte");
    static_assert(sizeof(bullet::GroupCode) == 1, "spawn group storage must be one byte");
    static_assert(BG_RING == 0x26 && BG_RING_AIMED == 0x2c);
    static_assert(BG_SPREAD == 0x2d && BG_SPREAD_AIMED == 0x2e);

    require_spread<5>(5, 0x10, {0x00, 0xf0, 0x10, 0xe0, 0x20});
    require_spread<4>(4, 0x10, {0x08, 0xf8, 0x18, 0xe8});
    require_spread<5>(5, 0x90, {0x00, 0x70, 0x90, 0xe0, 0x20});

    const std::array<unsigned, 8> ring{
        0x00, 0x20, 0x40, 0x60, 0x80, 0xa0, 0xc0, 0xe0
    };
    for (std::uint16_t member = 0; member < ring.size(); ++member) {
        require(
            bullet::ring_member_angle(member, std::uint8_t(ring.size())) ==
                ring[member],
            "ring angle mismatch"
        );
    }
    require(
        bullet::apply_aim_and_rotation(0xf0, true, 0x20, 0x08) == 0x18,
        "aim/template rotation wrap mismatch"
    );
    require(
        bullet::apply_aim_and_rotation(0xf0, false, 0x20, 0x08) == 0xf8,
        "un-aimed template rotation mismatch"
    );

    require(bullet::directional_sprite_cel(0x00) == 0, "right-facing cel mismatch");
    require(bullet::directional_sprite_cel(0x04) == 0, "rounded cel mismatch");
    require(bullet::directional_sprite_cel(0x05) == 1, "next cel mismatch");
    require(bullet::directional_sprite_cel(0x7c) == 15, "last cel mismatch");
    require(bullet::directional_sprite_cel(0x80) == 0, "half-turn reuse mismatch");

    bool rejected = false;
    try {
        (void)bullet::ring_member_angle(0, 0);
    } catch (const std::out_of_range&) {
        rejected = true;
    }
    require(rejected, "portable ring must reject count zero");

    randring::SharedRandomRing shared_random_ring;
    std::uint16_t generated_byte = 0;
    const auto fill_shared_random_ring = [&]() {
        generated_byte = 0;
        shared_random_ring.fill([&]() {
            return static_cast<std::uint8_t>(generated_byte++);
        });
        require(generated_byte == 256, "random-ring fill count mismatch");
        require(
            shared_random_ring.cursor() == 0,
            "random-ring fill cursor mismatch"
        );
    };
    fill_shared_random_ring();

    // Generated bytes 00..FF are stored at ring indexes 255..0. Alternating
    // plain, AND and MOD calls proves that every operation advances one state.
    require(
        shared_random_ring.next16() == 0xfeff,
        "random-ring first word mismatch"
    );
    require(shared_random_ring.next16_and(0x000f) == 0x000e,
            "random-ring AND reduction mismatch");
    require(shared_random_ring.next16_mod(100) == 65,
            "random-ring MOD reduction mismatch");
    require(
        shared_random_ring.cursor() == 3,
        "random-ring shared cursor mismatch"
    );

    fill_shared_random_ring();
    std::uint16_t last_ordinary_sample = 0;
    for (std::size_t i = 0; i < 255; ++i) {
        last_ordinary_sample = shared_random_ring.next16();
    }
    require(last_ordinary_sample == 0x0001,
            "random-ring last in-array sample mismatch");
    require(shared_random_ring.cursor() == 255,
            "random-ring pre-wrap cursor mismatch");
    require(shared_random_ring.next16() == 0xff00,
            "random-ring cursor-adjacent wrap sample mismatch");
    require(shared_random_ring.cursor() == 0,
            "random-ring low-byte wrap mismatch");
    require(shared_random_ring.next16() == 0xfeff,
            "random-ring post-wrap sequence mismatch");

    fill_shared_random_ring();
    bool zero_divisor_rejected = false;
    try {
        (void)shared_random_ring.next16_mod(0);
    } catch (const std::domain_error&) {
        zero_divisor_rejected = true;
    }
    require(zero_divisor_rejected, "random-ring zero divisor must fail");
    require(shared_random_ring.cursor() == 1,
            "random-ring zero divisor must consume its sample first");

    menu::State locked_menu;
    locked_menu.handle(menu::Input::down);
    require(
        locked_menu.selection() == std::uint8_t(menu::MainChoice::scores),
        "locked Extra must be skipped moving down"
    );
    locked_menu.handle(menu::Input::up);
    require(
        locked_menu.selection() == std::uint8_t(menu::MainChoice::game),
        "locked Extra must be skipped moving up"
    );

    menu::State unlocked_menu(true);
    unlocked_menu.handle(menu::Input::down);
    require(
        unlocked_menu.selection() == std::uint8_t(menu::MainChoice::extra),
        "unlocked Extra must remain selectable"
    );

    menu::State option_menu;
    for (unsigned i = 0; i < 3; ++i) {
        option_menu.handle(menu::Input::down);
    }
    option_menu.handle(menu::Input::confirm);
    require(
        option_menu.screen() == menu::Screen::options &&
            option_menu.selection() == std::uint8_t(menu::OptionChoice::rank),
        "Option must enter at the Rank row"
    );
    option_menu.handle(menu::Input::left);
    require(option_menu.options().rank == 0, "rank left transition mismatch");
    option_menu.handle(menu::Input::left);
    require(option_menu.options().rank == 3, "rank wrap mismatch");
    option_menu.handle(menu::Input::down);
    option_menu.handle(menu::Input::left);
    option_menu.handle(menu::Input::left);
    option_menu.handle(menu::Input::left);
    require(option_menu.options().lives == 6, "lives wrap mismatch");
    option_menu.handle(menu::Input::down);
    option_menu.handle(menu::Input::right);
    require(option_menu.options().bombs == 0, "bombs wrap mismatch");
    option_menu.handle(menu::Input::down);
    option_menu.handle(menu::Input::right);
    require(option_menu.options().bgm_mode == 0, "BGM wrap mismatch");
    option_menu.handle(menu::Input::down);
    option_menu.handle(menu::Input::right);
    require(option_menu.options().se_mode == 0, "SE right order mismatch");
    option_menu.handle(menu::Input::right);
    require(option_menu.options().se_mode == 2, "SE right BEEP transition mismatch");
    option_menu.handle(menu::Input::left);
    require(option_menu.options().se_mode == 0, "SE left order mismatch");
    option_menu.handle(menu::Input::down);
    option_menu.handle(menu::Input::confirm);
    require(!option_menu.options().turbo, "confirm must toggle Turbo");
    option_menu.handle(menu::Input::down);
    option_menu.handle(menu::Input::confirm);
    require(option_menu.options() == menu::Options{}, "Reset defaults mismatch");
    option_menu.handle(menu::Input::down);
    option_menu.handle(menu::Input::confirm);
    require(
        option_menu.screen() == menu::Screen::main &&
            option_menu.selection() == std::uint8_t(menu::MainChoice::options),
        "Option Quit must return to the Option command"
    );
    const auto quit = option_menu.handle(menu::Input::cancel);
    require(quit.kind == menu::ResultKind::quit, "main Cancel must quit");

    application::State app;
    require(
        app.program() == application::Program::op && app.generation() == 1,
        "portable application must begin in OP"
    );
    menu::Options custom_options;
    custom_options.lives = 5;
    custom_options.bombs = 1;
    custom_options.rank = 3;
    app.apply_options(custom_options);
    app.start_normal(
        application::Playchar::marisa, application::ShotType::b
    );
    require(
        app.program() == application::Program::main &&
            app.generation() == 2 && app.resident().stage == 0 &&
            app.resident().resource_stage == 0 &&
            app.resident().credit_lives == 5 &&
            app.resident().credit_bombs == 1 &&
            app.resident().playchar == application::Playchar::marisa &&
            app.resident().shot_type == application::ShotType::b &&
            app.resident().demo_number == 0 &&
            app.resident().end_sequence == application::EndSequence::in_game,
        "normal OP-to-MAIN resident contract mismatch"
    );

    bool invalid_transition_rejected = false;
    try {
        app.start_normal(
            application::Playchar::reimu, application::ShotType::a
        );
    } catch (const std::logic_error&) {
        invalid_transition_rejected = true;
    }
    require(
        invalid_transition_rejected,
        "MAIN must reject an OP-only launch transition"
    );

    application::RunStatistics statistics;
    statistics.score_digits = {1, 2, 3, 4, 5, 6, 7, 8};
    statistics.std_frames = 111;
    statistics.items_spawned = 222;
    statistics.items_collected = 123;
    statistics.point_items_collected = 77;
    statistics.max_valued_point_items_collected = 44;
    statistics.enemies_gone = 33;
    statistics.enemies_killed = 22;
    statistics.slow_frames = 0x12345678u;
    statistics.frames = 0x23456789u;
    app.finish_main(statistics, application::EndSequence::good);
    require(
        app.program() == application::Program::maine &&
            app.generation() == 3 &&
            app.maine_route() == application::MaineRoute::ending &&
            app.resident().end_type_ascii == '0' &&
            app.resident().score_digits == statistics.score_digits &&
            app.resident().statistics.frames == statistics.frames &&
            app.resident().statistics.slow_frames == statistics.slow_frames,
        "MAIN-to-MAINE publication contract mismatch"
    );
    app.finish_maine();
    require(
        app.program() == application::Program::op && app.generation() == 4 &&
            app.resident().score_digits == statistics.score_digits,
        "MAINE-to-OP resident retention mismatch"
    );

    app.start_normal(
        application::Playchar::marisa, application::ShotType::a
    );
    app.finish_main(statistics, application::EndSequence::bad);
    require(
        app.maine_route() == application::MaineRoute::ending &&
            app.resident().end_type_ascii == '1',
        "Bad Ending MAINE variant mismatch"
    );
    app.finish_maine();

    app.start_extra(
        application::Playchar::reimu, application::ShotType::a
    );
    require(
        app.resident().stage == 6 && app.resident().resource_stage == 6 &&
            app.resident().credit_lives == 3 &&
            app.resident().credit_bombs == 2,
        "Extra fixed-resource contract mismatch"
    );
    app.finish_main(statistics, application::EndSequence::extra);
    require(
        app.maine_route() == application::MaineRoute::extra,
        "Extra MAINE route mismatch"
    );
    app.finish_maine();

    app.start_normal(
        application::Playchar::reimu, application::ShotType::a
    );
    app.finish_main(statistics, application::EndSequence::score);
    require(
        app.maine_route() == application::MaineRoute::score_registration,
        "score-only MAINE route mismatch"
    );
    app.finish_maine();

    const std::array<std::uint8_t, 4> demo_stages{3, 0, 2, 1};
    const std::array<application::Playchar, 4> demo_characters{
        application::Playchar::reimu,
        application::Playchar::marisa,
        application::Playchar::reimu,
        application::Playchar::marisa,
    };
    const std::array<application::ShotType, 4> demo_shots{
        application::ShotType::a,
        application::ShotType::a,
        application::ShotType::b,
        application::ShotType::b,
    };
    for (std::size_t i = 0; i < demo_stages.size(); ++i) {
        app.start_next_demo();
        require(
            app.program() == application::Program::main &&
                app.resident().stage == 0 &&
                app.resident().resource_stage == demo_stages[i] &&
                app.resident().demo_stage == demo_stages[i] &&
                app.resident().demo_number == i + 1 &&
                app.resident().playchar == demo_characters[i] &&
                app.resident().shot_type == demo_shots[i] &&
                app.resident().credit_lives == 3 &&
                app.resident().credit_bombs == 3,
            "demo resident contract mismatch"
        );
        app.return_from_main(statistics);
        require(
            app.program() == application::Program::op,
            "demo completion must return directly to OP"
        );
    }
    app.start_next_demo();
    require(
        app.resident().demo_number == 1 &&
            app.resident().resource_stage == 3,
        "demo cycle must wrap from four to one"
    );
    app.return_from_main(statistics);
    app.exit_from_op();
    require(
        app.program() == application::Program::exited,
        "OP exit transition mismatch"
    );

    std::cout << "TH04 portable contracts: PASS pointer_bits="
              << sizeof(void*) * 8 << " angle_bits=" << sizeof(bullet::Angle) * 8
              << " menu_state=OP handoff_state=OP_MAIN_MAINE"
              << " randring=SHARED_OVERLAP" << std::endl;
    return 0;
}
