void near staffroll_animate(void)
{
	PaletteTone = 0;
	palette_show();
	graph_accesspage(1);
	pi_load(0, aSff1_pi);
	pi_palette_apply(0);
	pi_put_8(0, 0, 0);
	pi_free(0);
	graph_copy_page(0);
	bgimage_snap();
	snd_kaja_func(KAJA_SONG_STOP, 0);
	snd_load(aStaff, SND_LOAD_SONG);
	snd_kaja_func(KAJA_SONG_PLAY, 0);
	palette_black_in(12);
	cdg_load_single(0, aSff1_cdg, 0);
	cdg_load_single_noalpha(1, aSff1b_cdg, 0);
	snd_delay_until_measure(3, 64);
	cdg_slot = 0;
	dissolve_put_func = staffroll_dissolve_radial_put;
	staffroll_dissolve_out(352, 160);
	cdg_load_single(2, aSff2_cdg, 0);
	cdg_load_single_noalpha(3, aSff2b_cdg, 0);
	snd_delay_until_measure(7, 160);
	dissolve_put_func = staffroll_dissolve_diagonal_put;
	staffroll_dissolve_in(352, 160);
	cdg_slot = 2;
	dissolve_put_func = staffroll_dissolve_axis_put;
	staffroll_dissolve_out(192, 128);
	graph_accesspage(0);
	cdg_slot = 0;
	cdg_load_single(0, aSff3_cdg, 0);
	cdg_load_single_noalpha(1, aSff3b_cdg, 0);
	snd_delay_until_measure(11, 160);
	staffroll_dissolve_out(288, 200);
	snd_delay_until_measure(19, 160);
	dissolve_put_func = staffroll_dissolve_diagonal_put;
	staffroll_dissolve_two(192, 128, 288, 200);
	palette_black_out(4);
	cdg_free_all();
	graph_accesspage(1);
	pi_load(0, aSff2_pi);
	pi_palette_apply(0);
	pi_put_8(0, 0, 0);
	pi_free(0);
	graph_copy_page(0);
	bgimage_snap();
	palette_black_in(4);
	cdg_load_single(2, aSff4_cdg, 0);
	cdg_load_single_noalpha(3, aSff4b_cdg, 0);
	snd_delay_until_measure(23, 160);
	cdg_slot = 2;
	dissolve_put_func = staffroll_dissolve_axis_put;
	staffroll_dissolve_out(32, 112);
	cdg_free(2);
	cdg_load_single(4, aSff5_cdg, 0);
	cdg_load_single_noalpha(5, aSff5b_cdg, 0);
	snd_delay_until_measure(27, 160);
	cdg_slot = 4;
	dissolve_put_func = staffroll_dissolve_diagonal_put;
	staffroll_dissolve_out(32, 184);
	cdg_load_single(0, aSff8_cdg, 0);
	cdg_load_single_noalpha(1, aSff8b_cdg, 0);
	snd_delay_until_measure(31, 160);
	dissolve_put_func = staffroll_dissolve_axis_put;
	staffroll_dissolve_in(32, 184);
	cdg_slot = 0;
	staffroll_dissolve_out(64, 184);
	cdg_load_single(4, aSff9_cdg, 0);
	cdg_load_single_noalpha(5, aSff9b_cdg, 0);
	snd_delay_until_measure(35, 160);
	dissolve_put_func = staffroll_dissolve_radial_put;
	staffroll_dissolve_in(64, 184);
	cdg_slot = 4;
	staffroll_dissolve_out(64, 184);
	cdg_load_single(0, aSff6_cdg, 0);
	cdg_load_single_noalpha(1, aSff6b_cdg, 0);
	snd_delay_until_measure(39, 160);
	dissolve_put_func = staffroll_dissolve_diagonal_put;
	staffroll_dissolve_in(64, 184);
	cdg_slot = 0;
	staffroll_dissolve_out(32, 184);
	snd_delay_until_measure(43, 160);
	dissolve_put_func = staffroll_dissolve_axis_put;
	staffroll_dissolve_two(32, 112, 32, 184);
	cdg_load_single(0, aSff7_cdg, 0);
	cdg_load_single_noalpha(1, aSff7b_cdg, 0);
	cdg_slot = 0;
	staffroll_dissolve_out(32, 336);
	snd_delay_until_measure(48, 160);
	bgimage_free();
	cdg_free_all();
	palette_black_out(4);
}
