#!/usr/bin/env python3
"""Generate the human-readable TH04 boundary-review report from its ledger."""

from __future__ import annotations

import argparse
from collections import Counter
import csv
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[2]
LEDGER = ROOT / "config" / "th04_function_boundaries.csv"
OUTPUT = ROOT / "docs" / "BOUNDARY_REVIEW.md"
ARTIFACTS = ("th04-op", "th04-main", "th04-maine", "th04-zun")


def rows() -> list[dict[str, str]]:
    with LEDGER.open(newline="", encoding="utf-8") as stream:
        return list(csv.DictReader(stream))


def count_table(all_rows: list[dict[str, str]]) -> str:
    lines = [
        "| Artifact | Observations | Author candidates | Exact | Blocked | Unreviewed | ASM attestation | Excluded |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for artifact in ARTIFACTS:
        selected = [row for row in all_rows if row["artifact"] == artifact]
        queue = Counter(row["work_queue"] for row in selected)
        authored = [row for row in selected if row["work_queue"] == "reconstruct"]
        states = Counter(row["accepted_state"] for row in authored)
        lines.append(
            f"| `{artifact}` | {len(selected):,} | {len(authored):,} | "
            f"{states['exact']:,} | {states['blocked']:,} | {states['unreviewed']:,} | "
            f"{queue['attest-asm']:,} | {queue['exclude']:,} |"
        )
    selected = all_rows
    queue = Counter(row["work_queue"] for row in selected)
    authored = [row for row in selected if row["work_queue"] == "reconstruct"]
    states = Counter(row["accepted_state"] for row in authored)
    lines.append(
        f"| **Total** | **{len(selected):,}** | **{len(authored):,}** | "
        f"**{states['exact']:,}** | **{states['blocked']:,}** | "
        f"**{states['unreviewed']:,}** | **{queue['attest-asm']:,}** | "
        f"**{queue['exclude']:,}** |"
    )
    return "\n".join(lines)


def source_form_table(all_rows: list[dict[str, str]]) -> str:
    forms = (
        "target-derived-asm", "candidate-cpp", "candidate-c",
        "cross-game-candidate-cpp", "cross-game-candidate-c",
    )
    lines = [
        "| Artifact | Target-derived ASM | Candidate C++ | Candidate C | Cross-game C/C++ |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]
    for artifact in ARTIFACTS:
        selected = [
            row for row in all_rows
            if row["artifact"] == artifact
            and row["work_queue"] == "reconstruct"
            and row["accepted_state"] == "unreviewed"
        ]
        counts = Counter(row["source_form"] for row in selected)
        cross_game = counts["cross-game-candidate-cpp"] + counts["cross-game-candidate-c"]
        lines.append(
            f"| `{artifact}` | {counts[forms[0]]:,} | {counts[forms[1]]:,} | "
            f"{counts[forms[2]]:,} | {cross_game:,} |"
        )
    return "\n".join(lines)


def confidence_table(all_rows: list[dict[str, str]]) -> str:
    lines = [
        "| Artifact | Reviewed | Corroborated | Provisional |",
        "| --- | ---: | ---: | ---: |",
    ]
    for artifact in ARTIFACTS:
        selected = [
            row for row in all_rows
            if row["artifact"] == artifact and row["work_queue"] == "reconstruct"
        ]
        counts = Counter(row["boundary_state"] for row in selected)
        lines.append(
            f"| `{artifact}` | {counts['reviewed']:,} | {counts['corroborated']:,} | "
            f"{counts['provisional']:,} |"
        )
    return "\n".join(lines)


def render() -> str:
    all_rows = rows()
    authored = [row for row in all_rows if row["work_queue"] == "reconstruct"]
    authored_states = Counter(row["accepted_state"] for row in authored)
    nonexact = len(authored) - authored_states["exact"]
    asm_count = sum(row["work_queue"] == "attest-asm" for row in all_rows)
    return f"""# TH04 artifact boundary review

Generated by `python3 scripts/boundary_review/report_function_boundaries.py` from
`config/th04_function_boundaries.csv`.

## Result

Every function-like observation currently exposed by the four attested target
views, every code public in the cold candidate MAP files, and every local `PROC`
in the reviewed target-derived assembly inputs has an explicit ledger outcome.
This closes the inventory/classification pass; it does **not** promote the
remaining candidate boundaries or source to exact.

{count_table(all_rows)}

The remaining reconstruction queue is **{nonexact:,} nonexact authored candidates**:
{authored_states['unreviewed']:,} are unreviewed; {authored_states['blocked']:,} known
`MAIN.EXE` functions remain blocked.
Compiler startup, Borland runtime, MASTER.LIB, embedded library code, data/BSS
false positives, and Ghidra switch-case artifacts are excluded from that queue.
The {asm_count:,} original-style ASM observations remain a separate attestation queue.

## Remaining authored queue

{source_form_table(all_rows)}

`target-derived-asm` means an IDA/ReC98 assembly body identifies a likely game
function boundary; it does not claim that the original developer wrote that
function in assembly. Cross-game candidate source is corroboration only and
must be localized under TH04 ownership or proved `src/shared/` ownership before
it enters the standalone product build.

## Boundary confidence

{confidence_table(all_rows)}

- `reviewed` is inherited only from the accepted MAIN function ledger or a
  configured exact composite entry.
- `corroborated` means target Ghidra control flow agrees at the entry with a
  candidate TLINK public or TASM `PROC`, and the Ghidra body stays inside that
  ownership contribution.
- `provisional` is an intentionally retained candidate requiring focused raw
  control-flow/return/tail/table review before reconstruction or promotion.
- `excluded` remains visible in the ledger so a future agent cannot silently
  reintroduce runtime/library/data/switch artifacts as authored functions.

No byte percentage is derived from this ledger. Ghidra bodies may be sparse,
overlapping, or own trailing compiler tables differently; only accepted owner
extents in `config/units.csv` can contribute exact byte totals.

## Artifact-specific evidence

- `MAIN.EXE` is inspected directly from the hash-attested target and reconciled
  against its candidate MAP and TASM listings. A narrow function override keeps
  the game-owned `sub_3680` MPN renderer out of the surrounding `_TEXT`
  MASTER.LIB exclusion; target Ghidra and the emitting TASM `PROC` agree on its
  contiguous `0x75`-byte extent.
- Packed `OP.EXE` and `MAINE.EXE` are executed only through their own DIET
  decompressor stub at two load segments. The identical unrelocated payload is
  analyzed in a private hybrid MZ view; candidate header/relocation topology is
  diagnostic and not an original-unpacked-EXE claim.
- Packed `ZUN.COM` yields a 13,422-byte flat composite payload that is raw exact
  to the cold candidate pipeline. Its selector, `ongchk.com`, `zuninit.com`,
  `res_huma.com`, `memchk.com`, move-up stub, and customization stub are tracked
  as separate configured regions.
- Candidate MAP/source ownership is corroboration. The active target remains
  `candidate-local-attested`, so official pristine provenance is still open.

## Replay

```bash
python3 scripts/boundary_review/unpack_diet.py th04-op
python3 scripts/boundary_review/unpack_diet.py th04-maine
python3 scripts/boundary_review/unpack_diet.py th04-zun
python3 scripts/boundary_review/prepare_analysis_images.py \\
  --candidate-bin-dir COLD_REC98_ROOT/bin/th04
python3 scripts/boundary_review/export_ghidra_inventory.py ARTIFACT IMAGE \\
  --format mz import
python3 scripts/boundary_review/export_tasm_function_boundaries.py \\
  --candidate-source-root COLD_REC98_ROOT
python3 scripts/boundary_review/build_function_boundary_ledger.py \\
  --candidate-source-root COLD_REC98_ROOT
python3 scripts/boundary_review/validate_function_boundary_ledger.py
python3 scripts/boundary_review/report_function_boundaries.py --check
```

Ghidra projects and all generated target/listing/export material stay in ignored
private directories. Only the deterministic scripts, policy, ledger, and this
report are tracked.
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != content:
            print(f"error: stale generated boundary report: {OUTPUT.relative_to(ROOT)}")
            return 1
        print("boundary review report is current")
        return 0
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
