#!/usr/bin/env python3
"""Generate the conservative TH04 reconstruction progress snapshot."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
import tomllib

from status import artifact_report


ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "config"
OUTPUT = ROOT / "docs" / "PROGRESS.md"
SVG = ROOT / "resources" / "progress.svg"


def csv_rows(name: str) -> list[dict[str, str]]:
    with (CONFIG / name).open(newline="", encoding="utf-8") as stream:
        return list(csv.DictReader(stream))


def measures() -> dict[str, object]:
    all_units = csv_rows("units.csv")
    units = [row for row in all_units if row["artifact"] == "th04-main"]
    functions = csv_rows("th04_main_authored_functions.csv")
    reviewed_functions = [
        row for row in functions if row["boundary_state"] in {"reviewed", "shared"}
    ]
    boundaries = csv_rows("th04_function_boundaries.csv")
    targets = tomllib.loads((CONFIG / "targets.toml").read_text(encoding="utf-8"))
    reports = {
        artifact["id"]: artifact_report(artifact, all_units, functions, boundaries)
        for artifact in targets["artifacts"] if artifact["game"] == "th04"
    }
    authored_boundaries = [
        row for row in boundaries if row["work_queue"] == "reconstruct"
    ]
    corroborated_boundaries = [
        row
        for row in authored_boundaries
        if row["boundary_state"] in {"reviewed", "corroborated"}
    ]
    authored_units = [
        row
        for row in units
        if row["origin"] == "authored"
        and row["boundary_state"] in {"reviewed", "shared"}
        and row["state"] != "excluded"
    ]
    original_asm = [
        row
        for row in units
        if row["origin"] == "original-asm"
        and row["boundary_state"] in {"reviewed", "shared"}
        and row["state"] == "exact"
    ]
    return {
        "artifacts": reports,
        "functions": len(authored_boundaries),
        "review": len(authored_boundaries) - len(corroborated_boundaries),
        "authored": len(corroborated_boundaries),
        "implemented": sum(bool(row["source"]) for row in reviewed_functions),
        "matches": sum(row["state"] == "exact" for row in reviewed_functions),
        "exact_bytes": sum(
            int(row["size"], 0)
            for row in authored_units
            if row["state"] == "exact"
        ),
        "authored_bytes": sum(int(row["size"], 0) for row in authored_units),
        "reviewed": len(corroborated_boundaries),
        "original_asm": len(original_asm),
        "original_asm_bytes": sum(int(row["size"], 0) for row in original_asm),
    }


def render() -> str:
    values = measures()
    reports = values["artifacts"]
    exact_pct = (
        100 * values["exact_bytes"] / values["authored_bytes"]
        if values["authored_bytes"]
        else 0.0
    )
    rows = []
    for artifact_id, report in reports.items():
        boundary = report["authored_boundary_states"]
        accepted = report["authored_candidate_states"]
        rows.append(
            f"| `{artifact_id}` | {report['authored_function_candidates']} | "
            f"{boundary.get('reviewed', 0)} | {boundary.get('corroborated', 0)} | "
            f"{boundary.get('provisional', 0)} | "
            f"{report['accepted_exact_authored_functions']} | "
            f"{accepted.get('blocked', 0)} | {accepted.get('unreviewed', 0)} | "
            f"{report['unresolved_target_derived_asm_candidates']} | "
            f"{report['original_asm_attestation_candidates']} |"
        )
    total = {
        "candidates": sum(r["authored_function_candidates"] for r in reports.values()),
        "reviewed": sum(r["authored_boundary_states"].get("reviewed", 0) for r in reports.values()),
        "corroborated": sum(r["authored_boundary_states"].get("corroborated", 0) for r in reports.values()),
        "provisional": sum(r["authored_boundary_states"].get("provisional", 0) for r in reports.values()),
        "exact": sum(r["accepted_exact_authored_functions"] for r in reports.values()),
        "blocked": sum(r["authored_candidate_states"].get("blocked", 0) for r in reports.values()),
        "unreviewed": sum(r["authored_candidate_states"].get("unreviewed", 0) for r in reports.values()),
        "derived_asm": sum(r["unresolved_target_derived_asm_candidates"] for r in reports.values()),
        "asm": sum(r["original_asm_attestation_candidates"] for r in reports.values()),
    }
    rows.append(
        f"| **Total** | **{total['candidates']}** | **{total['reviewed']}** | "
        f"**{total['corroborated']}** | **{total['provisional']}** | "
        f"**{total['exact']}** | **{total['blocked']}** | "
        f"**{total['unreviewed']}** | **{total['derived_asm']}** | **{total['asm']}** |"
    )
    artifact_table = "\n".join(rows)
    return f"""# TH04 reconstruction progress

Generated by `python3 scripts/progress.py` from the live ledgers.

## All-artifact function routing

| Artifact | Authored candidates | Reviewed boundary | Corroborated only | Provisional | Function exact | Blocked | Unreviewed acceptance | Unresolved target-derived ASM | ASM attestation queue |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
{artifact_table}

`Corroborated` is not a completed physical boundary review. `Target-derived
ASM` describes unresolved candidate source representation, not proven original ASM
ownership; the separate ASM attestation queue is excluded from authored C/C++
byte percentages. The provisional column counts authored reconstruction
candidates only; ASM attestation entries may have provisional boundaries too.

## MAIN.EXE file-backed acceptance

| Measure | Count |
| --- | ---: |
| Source-present accepted `MAIN.EXE` mappings | {values['implemented']:,} |
| Accepted exact `MAIN.EXE` functions | {values['matches']:,} |
| Accepted exact authored bytes | {values['exact_bytes']:,} / {values['authored_bytes']:,} |
| Exact / confirmed MAIN authored bytes | {exact_pct:.2f}% |
| Exact original-style ASM units in MAIN | {values['original_asm']:,} / {values['original_asm_bytes']:,} bytes |

The MAIN byte percentage uses reviewed file-backed authored C/C++ owner extents,
not MAIN.EXE's complete file and not all TH04 artifacts. OP, MAINE, and ZUN
currently have no accepted packed-file byte denominator. Their decoded exact
function counts are checked against `config/th04_decoded_function_acceptance.csv`
and must not be read as packed raw-file exactness. Ghidra body sizes are
provisional until physical ownership is reviewed.
"""


def render_svg() -> str:
    values = measures()
    reports = values["artifacts"]
    exact_bytes = values["exact_bytes"]
    authored_bytes = values["authored_bytes"]
    exact_pct = 100 * exact_bytes / authored_bytes if authored_bytes else 0.0
    bar_width = 282

    def stacked_bar(x: int, y: int, total: int, parts: tuple[tuple[int, str], ...]) -> str:
        elements = [
            f'<rect x="{x}" y="{y}" width="{bar_width}" height="12" rx="4" fill="#353b52"/>'
        ]
        cursor = float(x)
        for count, color in parts:
            width = bar_width * count / total if total else 0.0
            if count:
                elements.append(
                    f'<rect x="{cursor:.2f}" y="{y}" width="{width:.2f}" '
                    f'height="12" fill="{color}"/>'
                )
            cursor += width
        return "\n  ".join(elements)

    display = (
        ("th04-op", "OP.EXE"),
        ("th04-main", "MAIN.EXE"),
        ("th04-maine", "MAINE.EXE"),
        ("th04-zun", "ZUN.COM"),
    )
    rows = []
    for index, (artifact_id, label) in enumerate(display):
        report = reports[artifact_id]
        total = report["authored_function_candidates"]
        boundary = report["authored_boundary_states"]
        accepted = report["authored_candidate_states"]
        reviewed = boundary.get("reviewed", 0)
        corroborated = boundary.get("corroborated", 0)
        provisional = boundary.get("provisional", 0)
        exact = accepted.get("exact", 0)
        blocked = accepted.get("blocked", 0)
        unreviewed = accepted.get("unreviewed", 0)
        y = 118 + index * 62
        rows.append(f'''<text x="24" y="{y + 10}" fill="#f4f4f5" font-family="sans-serif" font-size="14" font-weight="600">{label}</text>
  <text x="24" y="{y + 30}" fill="#c8cad2" font-family="monospace" font-size="11">{total} candidates</text>
  {stacked_bar(154, y + 3, total, ((reviewed, "#9b6de3"), (corroborated, "#5496d6"), (provisional, "#596078")))}
  {stacked_bar(476, y + 3, total, ((exact, "#55c7a6"), (blocked, "#f0a95c"), (unreviewed, "#596078")))}
  <text x="154" y="{y + 32}" fill="#c8cad2" font-family="monospace" font-size="11">R {reviewed} · C {corroborated} · P {provisional}</text>
  <text x="476" y="{y + 32}" fill="#c8cad2" font-family="monospace" font-size="11">Exact {exact} · Blocked {blocked} · Pending {unreviewed}</text>''')
    artifact_rows = "\n  ".join(rows)
    main_width = bar_width * exact_bytes / authored_bytes if authored_bytes else 0.0
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="788" height="440" role="img" aria-label="TH04 per-artifact reconstruction progress">
  <title>TH04 reconstruction progress by artifact</title>
  <desc>Each artifact has separate authored-boundary and function-acceptance bars. Only MAIN has a file-backed authored-byte percentage.</desc>
  <rect width="788" height="440" rx="8" fill="#1f2335"/>
  <text x="24" y="31" fill="#f4f4f5" font-family="sans-serif" font-size="18" font-weight="600">TH04 reconstruction progress</text>
  <text x="24" y="52" fill="#c8cad2" font-family="sans-serif" font-size="12">Two independent planes · authored function candidates only</text>
  <text x="154" y="83" fill="#f4f4f5" font-family="sans-serif" font-size="13" font-weight="600">Boundary confidence</text>
  <text x="476" y="83" fill="#f4f4f5" font-family="sans-serif" font-size="13" font-weight="600">Function acceptance</text>
  <text x="154" y="100" fill="#c8cad2" font-family="sans-serif" font-size="11">R reviewed · C corroborated · P provisional</text>
  <text x="476" y="100" fill="#c8cad2" font-family="sans-serif" font-size="11">Exact · blocked · pending</text>
  {artifact_rows}
  <path d="M24 366 H764" stroke="#4b526d"/>
  <text x="24" y="392" fill="#f4f4f5" font-family="sans-serif" font-size="13" font-weight="600">MAIN file-backed authored bytes only</text>
  <text x="764" y="392" fill="#c8cad2" text-anchor="end" font-family="monospace" font-size="12">{exact_bytes:,} / {authored_bytes:,} · {exact_pct:.2f}%</text>
  <rect x="24" y="402" width="{bar_width}" height="12" rx="4" fill="#353b52"/>
  <rect x="24" y="402" width="{main_width:.2f}" height="12" fill="#9b6de3"/>
  <text x="330" y="413" fill="#c8cad2" font-family="sans-serif" font-size="11">OP / MAINE / ZUN packed-file byte denominator: n/a</text>
</svg>
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    svg = render_svg()
    if args.check:
        stale: list[str] = []
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            stale.append(str(OUTPUT.relative_to(ROOT)))
        if not SVG.exists() or SVG.read_text(encoding="utf-8") != svg:
            stale.append(str(SVG.relative_to(ROOT)))
        if stale:
            print("error: stale generated progress: " + ", ".join(stale))
            return 1
        print("progress artifacts are current")
        return 0
    OUTPUT.write_text(content, encoding="utf-8")
    SVG.parent.mkdir(parents=True, exist_ok=True)
    SVG.write_text(svg, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} and {SVG.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
